version: "3"

services:
  vuejs:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - API_ENDPOINT=${API_ENDPOINT}
    environment:
      - HOST=vuejs
      - PORT=80
    volumes:
      - ./app/src:/app/src
      - ./app/test:/app/test
      - ./app/static:/app/static
      - ./app/package.json:/app/package.json
    ports:
      - "80:80"