FROM node:lts-alpine
ARG API_ENDPOINT

WORKDIR /app/

RUN apk add gettext

COPY ./app/package.json ./package.json
RUN npm install -g vue-cli
RUN npm install

COPY ./app/ ./

RUN envsubst '\$API_ENDPOINT' < config/dev.env.js > config/dev.env.js.tmp
RUN mv config/dev.env.js.tmp config/dev.env.js

CMD [ "npm", "run", "dev" ]